version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm run dev
    env_file:
      - ./server/.env

  client:
    build: ./client
    ports:
      - "3000:3000"
    working_dir: /app
    env_file:
    - ./client/.env.production

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
